# Generated by Django 4.0.7 on 2022-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('talaba_soni', models.IntegerField(default=100)),
                ('dekan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('modul', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Institut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fakultet_soni', models.IntegerField(default=5)),
                ('name_rektor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sinf', models.IntegerField(default=1)),
                ('sinf_raxbar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Olimpiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yunalish', models.CharField(max_length=20)),
                ('qatnashuvchilar', models.IntegerField(default=10)),
                ('time', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
    ]
